### ISSUE TITLE
Remove sourcemaps from production builds

### ISSUE THREAD

**Issue by josephabrahams** [istrategylabs/mo-static#13]

**Comment by akrawchyk** [comment]
Production builds are piped through minifiers which remove source maps. How are you building to get sourcemaps in prod files?

**Comment by josephabrahams** [comment]
Think the minifier wasn't working at that point.

Good to close.

Joseph Abrahams | VP of Engineering
ISL <https://isl.co/> | 256.302.0500
Twitter <http://twitter.com/josephabrahams> | LinkedIn <https://www.linkedin.com/in/josephabrahams>
