### ISSUE TITLE
Update cookiecutter defaults

### ISSUE THREAD

**Issue by josephabrahams** [istrategylabs/mo-static#17]
1. Remove repo_name - use project name to create repo name (is this possible?)
2. Remove default description

**Comment by akrawchyk** [comment]
`Remove repo_name - use project name to create repo name (is this possible?)`

I don't think we can remove the `repo_name` variable, we'd still need it to be available in the context for the project template. There's no way to add it without prompting the user:
* The only support for adding [extra context context](https://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#injecting-extra-context) is to use Cookiecutter programmatically.
* You can't [suppress input prompts](https://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#suppressing-command-line-prompts) for a single variable, it must be all of them

We could [validate the variable](https://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#example-validating-template-variables) in the `pre_gen_project` hook though.

**Comment by akrawchyk** [comment]
`Remove default description`

Fixed by https://github.com/istrategylabs/mo-static/commit/80c20d03a6b905b6702b4619dced6771e2ee3e63

**Comment by josephabrahams** [comment]
Think you're right. Maybe ping @jcarbaugh and stay consistent w/ mo-djagno.

**Comment by jcarbaugh** [comment]
We're both creating a default `repo_name` from `project_name`: https://github.com/istrategylabs/mo-django/blob/master/cookiecutter.json#L3

Andrew is right that there isn't a way to suppress the prompt, but the default will be set correctly for people to just return through.

**Comment by akrawchyk** [comment]
@jcarbaugh thanks for checking! Closing for now.
