### ISSUE TITLE
Remove post_install hook

### ISSUE THREAD

**Issue by josephabrahams** [istrategylabs/mo-static#18]
We should be using NVM. As such, the required version of Node must be installed before `npm install` is run. Therefore, users should probably run `nvm use` and `npm install` manually.

**Comment by akrawchyk** [comment]
The `postinstall` hook is so damn convenient! Makes sense to me though, I've updated the docs re: nvm.

**Comment by akrawchyk** [comment]
Fixed by #29 and #30
