### ISSUE TITLE
Consistently name main css & js file

### ISSUE THREAD

**Issue by josephabrahams** [istrategylabs/mo-static#19]
JS is project_name.js and css is main.css? Can we make them consistent? [app | main]

**Comment by akrawchyk** [comment]
Pick one? I like app, it's shorter.

**Comment by josephabrahams** [comment]
app. done.

Joseph Abrahams | VP of Engineering
ISL <https://isl.co/> | 256.302.0500
Twitter <http://twitter.com/josephabrahams> | LinkedIn <https://www.linkedin.com/in/josephabrahams>

**Comment by akrawchyk** [comment]
Fixed by #31
