### ISSUE TITLE
Extras should be copied to public_path

### ISSUE THREAD

**Issue by akrawchyk** [istrategylabs/mo-static#2]
As a developer, I want my extra assets that are not preprocessed to be available to my front-end, so I can reference these assets when deployed.

Extras include:

* .txt
* .json
* .xml
* .png .gif .jpg

**Comment by thomasdegry** [comment]
We're adding svg to that list too, right?

**Comment by akrawchyk** [comment]
Yea .svg too. I think everything should just be copied over as is from the `src` dir. That way we don't have to adjust the paths when we build it.

**Comment by thomasdegry** [comment]
K cool, I got it up and running. Submitting a PR later today

**Comment by akrawchyk** [comment]
Fixed by #3
