### ISSUE TITLE
Built assets should be cache-busted

### ISSUE THREAD

**Issue by akrawchyk** [istrategylabs/mo-static#4]
As a developer, I want my built assets file names to include version hashes and replace the asset references with these names, so I can cache-bust new deploys.

@josephabrahams we're going to skip on generating an asset manifest for now. Let me know if you think we need it.

* Use https://github.com/sindresorhus/gulp-rev to add version hashes to all assets except `*.html`
* Use https://github.com/jamesknelson/gulp-rev-replace to replace references to these assets with their cache-busted counterparts.

**Comment by josephabrahams** [comment]
:+1:

**Comment by akrawchyk** [comment]
Fixed by #7
