### ISSUE TITLE
Vueify Proposal

### ISSUE THREAD

**Issue by recursivefunk** [istrategylabs/mo-static#52]
PR https://github.com/istrategylabs/mo-static/pull/56

Investigate the use of [Vueify](https://github.com/vuejs/vueify) to accomplish something along the lines of

```
components/
   foo/
      index.vue
      style.scss
      template.html
   bar/
      index.vue
      style.scss
      template.html
```

Where `index.vue` imports it's own styles and template (or something like that just spit-balling here). We'd need to research how to handle global styles

**Comment by akrawchyk** [comment]
@recursivefunk i'm interested in implementing this with a cookiecutter flag

**Comment by recursivefunk** [comment]
Yea I meant to mention it as an option not by default @akrawchyk
