### ISSUE TITLE
Add default extras

### ISSUE THREAD

**Issue by akrawchyk** [istrategylabs/mo-static#6]
@josephabrahams What extras do you want by default in the project? We already have a few of these, but I'm looking at what's included in https://github.com/h5bp/html5-boilerplate/tree/master/dist as a reference. I'm thinking:

* humans.txt
* 404.html
* favicon.ico
* other favicons per https://github.com/audreyr/favicon-cheat-sheet#optional-but-encouraged
* robots.txt

**Comment by josephabrahams** [comment]
Something I'm struggling with: Should we remove all the references to ISL from these repos (i.e. humans.txt, etc.) and add that stuff manually? If we're aiming for these to be adopted outside of ISL then perhaps they should be a bit more generic. Thoughts? @jcarbaugh @jray

**Comment by jray** [comment]
Yea depends on our end goal. If we're developing FOR open source and just using this stuff then yep, take it out. On the other hand if we're just developing ISL stuff in the open, then it's fine to keep in and other folks can change it.

**Comment by akrawchyk** [comment]
I'm going to add a `favicon.ico` in the root of the build by default in order to stop getting 404's on page load.

**Comment by jcarbaugh** [comment]
I think these project templates need to be specific to our needs so we should be developing in the open, not developing for general use. mo repos can serve as examples, not necessarily usable by others without modification.

**Comment by akrawchyk** [comment]
Related discussion at https://github.com/istrategylabs/mo-static/pull/23#issuecomment-194421555

**Comment by akrawchyk** [comment]
I added `humans.txt`, `robots.txt`, and updated the favicons.
