### ISSUE TITLE
Possible nconf bug

### ISSUE THREAD

**Issue by oudeismetis** [istrategylabs/mo-static#62]
Was updating a project with the latest mo-static (all changes since mid-June) and got the following error.
![image](https://cloud.githubusercontent.com/assets/444070/17418005/3caa647c-5a64-11e6-9645-cc4c8b64b0b7.png)

reverting my config.js to the old version fixed things. All of the other updates were fine.

**Comment by akrawchyk** [comment]
This should be resolved once we merge #77
