### ISSUE TITLE
Replace browserify with webpack

### ISSUE THREAD

**Issue by akrawchyk** [istrategylabs/mo-static#71]

**Comment by akrawchyk** [comment]
TODO:
- [x] Remove browserify (and related packages) and replace with webpack
- [ ] Transform code with Babel (see https://github.com/survivejs/webpack/blob/dev/manuscript/building_with_webpack/04_processing_with_babel.md) @lee-anne-clarke 
- [ ] Integrate webpack with gulp (look at ) @j-baconator 
- [ ] Update configuration docs at https://github.com/istrategylabs/mo-static/tree/master/%7B%7Bcookiecutter.repo_name%7D%7D#configuration to replace browserify with webpack (this might require changes to nconf as well, depending on differences with webpack) @marissa-halpert 
- [ ] Investigate bundling foundation javascript (see https://github.com/survivejs/webpack/blob/dev/manuscript/advanced_techniques/01_consuming_packages.md) @thomasdegry

**Comment by thomasdegry** [comment]
I created a PR for the last one that you can find [here](https://github.com/istrategylabs/mo-static/pull/74)!

Also I noticed during making it that file watching seems to be broken, anyone else noticing?

**Comment by akrawchyk** [comment]
See https://github.com/istrategylabs/mo-static/pull/77 to follow along
