### ISSUE TITLE
Reduce CSS weight

### ISSUE THREAD

**Issue by akrawchyk** [istrategylabs/mo-static#75]
The CSS we ship by default (w/minimal Foundation components installed) isn't necessarily large, but might be bloated:

| Foundation | Size |
|---|---|
| Build | 294K |
| Minified | 34K |
| MInified w/Gzip | 6.6K |

By contrast, this is SUIT CSS:

| SUIT CSS | Size |
|---|---|
| Build | 44K |
| Minified | 20K |
| Minified w/Gzip | 3.9K |

However, SUIT CSS doesn't provide the breadth of components that Foundation does. But, SUIT CSS by design doesn't make design decisions for you out of the box.

**Comment by thomasdegry** [comment]
I'm all for; the only things I'm slightly concerned about are these:
- We need to find an easy-to-use, somewhat similar grid system to foundation's since that's the thing we use most I'd say
- A good normalizer that resets browser styles
- Ability to split components into multiple files (sass style)
- Maybe nesting?

**Comment by akrawchyk** [comment]
All good points, the first two are related to SUIT, the second two are more related to CSS preprocessors in general. Here's my take on them:

- the SUIT CSS grid is similar, at least as flexible, and still based on flexbox: https://github.com/suitcss/components-grid. You could combine it with https://github.com/suitcss/utils-size/ to get the traditional 12 column layout as well as sizing on different screen sizes.
- the SUIT CSS base module start with normalize first https://github.com/suitcss/base/blob/master/index.css#L1. Personally, I like adding https://github.com/kennethormandy/normalize-opentype.css as well, but that seems less well maintained.

- Splitting components into multiple files is a must-have. SASS or [SUIT preprocessor](https://github.com/suitcss/preprocessor) both provide this out of the box
- Nesting is so convenient to the developer it's pretty much a must-have as well. I don't think SUIT preprocessor provides this out of the box, but you can hook any [PostCSS plugin into the build process](https://github.com/suitcss/preprocessor#use) that you'd like. So, we could add [postcss-nested](https://github.com/postcss/postcss-nested) to get this feature.
